name: Debug and Fetch Package Versions

on:
  workflow_dispatch:

jobs:
  debug-package:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Organization Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching organization packages..."
        curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/orgs/Digitraffic-Infrastructure/packages?package_type=maven" > org_packages.json
        echo "Saved to org_packages.json"
        cat org_packages.json

    - name: Debug Repository Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching repository packages..."
        curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/Digitraffic-Infrastructure/Digitraffic.CentralRepository/packages?package_type=maven" > repo_packages.json
        echo "Saved to repo_packages.json"
        cat repo_packages.json

    - name: Fetch Versions for ETSILIB
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGE_ETSILIB: digitraffic.link.etsi:etsilibrary
      run: |
        echo "Fetching versions for $PACKAGE_ETSILIB..."
        curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/orgs/Digitraffic-Infrastructure/packages/maven/${PACKAGE_ETSILIB}/versions" > etsilib_versions.json
        echo "Saved to etsilib_versions.json"
        cat etsilib_versions.json
        
        echo "Extracting version..."
        VERSION=$(jq -r '.[0].metadata.container.tags[0] // "unknown"' etsilib_versions.json)
        echo "Fetched version: $VERSION"
        if [ "$VERSION" == "unknown" ]; then
          echo "Error: Could not fetch the version. Check the response."
          exit 1
        fi

    - name: Validate Token Permissions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Testing token permissions..."
        RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
          "https://api.github.com/rate_limit")
        echo "Rate limit response: $RESPONSE"
