name: Update README with Latest GitHub Package Version

on:
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3
        with:
          repository: 'Digitraffic-Infrastructure/.github'

      - name: Set up authentication for private repository
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Fetch latest package versions
        id: fetch-version
        run: |
          PACKAGE_ETSILIB="digitraffic.link.etsi:etsilibrary"
          PACKAGE_CONNECT="digitraffic.connect:connect"

          ETSILIB_VERSION=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/orgs/Digitraffic-Infrastructure/packages/container/digitraffic.link.etsi%3Aetsilibrary/versions" | jq -r '.[0].metadata.container.tags[0]')

          CONNECT_VERSION=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/orgs/Digitraffic-Infrastructure/packages/container/digitraffic.connect%3Aconnect/versions" | jq -r '.[0].metadata.container.tags[0]')

          echo "ETSILIB_VERSION=$ETSILIB_VERSION" >> $GITHUB_ENV
          echo "CONNECT_VERSION=$CONNECT_VERSION" >> $GITHUB_ENV

          if [ -z "$ETSILIB_VERSION" ] || [ -z "$CONNECT_VERSION" ]; then
            echo "Error: Failed to fetch latest versions."
            exit 1
          fi

      - name: Debugging Output
        run: |
          echo "Fetched ETSILIB_VERSION: $LATEST_VERSION_ETSILIB"
          echo "Fetched CONNECT_VERSION: $LATEST_VERSION_CONNECT"
          echo "Contents of README before update:"
          cat profile/README.md

      - name: Update README
        run: |
          sed -i "s/{{LATEST_VERSION_ETSILIB}}/$LATEST_VERSION_ETSILIB/g" profile/README.md
          sed -i "s/{{LATEST_VERSION_CONNECT}}/$LATEST_VERSION_CONNECT/g" profile/README.md
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git commit -m "Update README with latest versions: $LATEST_VERSION_ETSILIB, $LATEST_VERSION_CONNECT" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
