name: Update README with Latest Package Versions

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the `.github` repository where the README is stored
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Digitraffic-Infrastructure/.github

      # Define environment variables and fetch latest versions
      - name: Fetch Latest Package Versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_ETSILIB: "digitraffic.link.etsi:etsilibrary"
          PACKAGE_CONNECT: "digitraffic.connect:connect"
        run: |
          echo "Fetching package versions from Digitraffic.CentralRepository..."

          # Fetch ETSILIB version
          ETSILIB_VERSION=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Digitraffic-Infrastructure/Digitraffic.CentralRepository/packages/container/${PACKAGE_ETSILIB}/versions" | \
            jq -r '.[0].metadata.container.tags[0] // "unknown"')
          
          # Fetch CONNECT version
          CONNECT_VERSION=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Digitraffic-Infrastructure/Digitraffic.CentralRepository/packages/container/${PACKAGE_CONNECT}/versions" | \
            jq -r '.[0].metadata.container.tags[0] // "unknown"')

          echo "ETSILIB_VERSION=$ETSILIB_VERSION" >> $GITHUB_ENV
          echo "CONNECT_VERSION=$CONNECT_VERSION" >> $GITHUB_ENV

      # Debug API response if version fetching fails
      - name: Debug API Response for ETSILIB
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_ETSILIB: "digitraffic.link.etsi:etsilibrary"
        run: |
          echo "Debugging API response for ETSILIB..."
          curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Digitraffic-Infrastructure/Digitraffic.CentralRepository/packages/container/${PACKAGE_ETSILIB}/versions" > etsilib_response.json
          cat etsilib_response.json

      # Debug API response if version fetching fails
      - name: Debug API Response for CONNECT
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_CONNECT: "digitraffic.connect:connect"
        run: |
          echo "Debugging API response for CONNECT..."
          curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Digitraffic-Infrastructure/Digitraffic.CentralRepository/packages/container/${PACKAGE_CONNECT}/versions" > connect_response.json
          cat connect_response.json

      # Update the README
      - name: Update README with Versions
        if: success()
        env:
          ETSILIB_VERSION: ${{ env.ETSILIB_VERSION }}
          CONNECT_VERSION: ${{ env.CONNECT_VERSION }}
        run: |
          sed -i "s/{{LATEST_VERSION_ETSILIB}}/${ETSILIB_VERSION}/g" profile/README.md
          sed -i "s/{{LATEST_VERSION_CONNECT}}/${CONNECT_VERSION}/g" profile/README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git commit -m "Update README with latest package versions"
          git push
